spring.application.name=student-management

spring.datasource.url=jdbc:mysql://localhost:3306/school one?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=20250861230
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true
#让 MyBatis 自动把数据库里的下划线命名，映射成 Java 里的驼峰命名
