spring.application.name=student-management

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true
#让 MyBatis 自动把数据库里的下划线命名，映射成 Java 里的驼峰命名
#无需手写SELECT user_name AS userName, create_time AS createTime FROM user

logging.config=classpath:logback-spring.xml
#自定义logback配置文件
logging.level.root=INFO
#全局默认配置等级
logging.level.org.springframework=WARN
#Spring的框架日志 设置为warm减少噪音 只输出错误的

spring.profiles.active=prod